In [1]:
from scipy import stats
import statsmodels.api as sm

In [ ]:
stats.ttest_ind  # T-test for the means of *two independent* samples

In [ ]:
stats.ttest_rel  # t-test on TWO RELATED samples

In [2]:
import numpy as np

array([ 0.00982522, -0.01031647,  0.00645437, -0.00747867,  0.00297661,
        0.00190175,  0.00295987, -0.00242078,  0.01277846, -0.00912311])

In [80]:
x_1 = np.random.randn(10)*0.01

In [81]:
x_2 = x_1 + np.random.randn(len(x_1))*0.001 + 0.001

In [82]:
x_1

array([ 0.00625856, -0.00464712,  0.00985974, -0.00467698,  0.00608431,
        0.00576996, -0.01489922, -0.02722404, -0.00299737,  0.01105602])

In [83]:
x_2

array([ 0.00671383, -0.00285388,  0.01088672, -0.00280668,  0.00587298,
        0.00703278, -0.0136019 , -0.02472377, -0.00212677,  0.01160398])

In [84]:
stats.ttest_ind(x_1, x_2)  # 均值是否一致, H0: 没有差异， H1：存在差异。

Ttest_indResult(statistic=-0.21577179812037656, pvalue=0.8315918240512906)

In [85]:
stats.ttest_rel(x_1, x_2)   # 差值是否存在, H0:差值为0

TtestResult(statistic=-4.5833172431543066, pvalue=0.00132155292757038, df=9)